# Generated by Django 4.2.2 on 2023-06-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(),
        ),
    ]
